version: '3.8'

services:
  app:
    image: laravelapp
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    working_dir: /var/www
    volumes:
      - app-data:/var/www
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - app-data:/var/www
      - nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  app-data:
  db-data:
  nginx-conf:

networks:
  app-network:
    driver: overlay

